# Set theme
palette = "gruvbox_dark"

[character]
success_symbol = "[[](color_red) ❯](color_green)"
error_symbol = "[❯](color_red)"
vimcmd_symbol = "[❮](color_green)"

[directory]
truncation_length = 4
style = "bold color_aqua"
format = "[$path ]($style)"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
