# Set theme
palette = "gruvbox_dark"

format = """\
[\\[](color_red bold)\
$username\
[@](color_green bold)\
$hostname\
$directory\
[\\]](color_red bold)\
$git_branch\
$git_status\
$character\
"""

[character]
success_symbol = '[\$](color_fg0)'
error_symbol = '[\$](color_red)'
vimcmd_symbol = '[\$](color_green)'

[directory]
truncation_length = 4
style = "color_purple bold"
truncation_symbol = "…/"
format = "[ $path]($style)"

[username]
show_always = true
style_user = "color_yellow bold"
style_root = "color_yellow bold"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = "color_blue bold"
format = '[$hostname]($style)'
disabled = false

[git_branch]
style = "color_aqua bold"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "color_orange bold"
conflicted = "✖"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "…"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
