import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dimensions.columns = 216
dimensions.lines = 59
startup_mode = "Maximized"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 15
